# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Carrefour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carrefour

    pod 'RxSwift'
    pod 'RxCocoa'

  target 'CarrefourTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'CarrefourUITests' do
    # Pods for testing
  end

end
